name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18.x, 20.x]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run ESLint
      run: npm run lint

    - name: Run tests
      run: npm test -- --coverage --watchAll=false
      env:
        CI: true

    - name: Build application
      run: npm run build
      env:
        REACT_APP_MARKETAUX_API_KEY: ${{ secrets.REACT_APP_MARKETAUX_API_KEY }}
        REACT_APP_FINNHUB_API_KEY: ${{ secrets.REACT_APP_FINNHUB_API_KEY }}
        REACT_APP_STOCKNEWS_API_KEY: ${{ secrets.REACT_APP_STOCKNEWS_API_KEY }}
        REACT_APP_ALPHAVANTAGE_API_KEY: ${{ secrets.REACT_APP_ALPHAVANTAGE_API_KEY }}
        CI: false

    - name: Upload build artifacts
      if: matrix.node-version == '20.x'
      uses: actions/upload-artifact@v4
      with:
        name: build-files
        path: build/
        retention-days: 1

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build
      env:
        REACT_APP_MARKETAUX_API_KEY: ${{ secrets.REACT_APP_MARKETAUX_API_KEY }}
        REACT_APP_FINNHUB_API_KEY: ${{ secrets.REACT_APP_FINNHUB_API_KEY }}
        REACT_APP_STOCKNEWS_API_KEY: ${{ secrets.REACT_APP_STOCKNEWS_API_KEY }}
        REACT_APP_ALPHAVANTAGE_API_KEY: ${{ secrets.REACT_APP_ALPHAVANTAGE_API_KEY }}
        CI: false

    - name: Setup Pages
      uses: actions/configure-pages@v4

    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: build

    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
